version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3001:3001'
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    volumes:
      - .:/home/node/app
